[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "portfolio-chatbot"
version = "1.0.0"
description = "Portfolio Chatbot with WebSocket support"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["app"]