services:
  - type: web
    name: solai-portfolio-chat
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8000
    autoDeploy: true
